//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIISAConc.webControls.auditoria {
    
    
    public partial class ctrListaAuditoria {
        
        /// <summary>
        /// txtFechaAtencion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFechaAtencion;
        
        /// <summary>
        /// ctrEstadoAtenc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISA.Controls.estadoAtenc.ctrEstadoAtenc ctrEstadoAtenc;
        
        /// <summary>
        /// btnBuscarAtencEstab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnBuscarAtencEstab;
        
        /// <summary>
        /// ctrAtencEstablecidas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.concurrencia.CtrAtencEstablecidas ctrAtencEstablecidas;
    }
}
