//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIISAConc.Concurrencia {
    
    
    public partial class Auditoria {
        
        /// <summary>
        /// ctrAuditoria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.auditoria.ctrAuditoria ctrAuditoria;
        
        /// <summary>
        /// ctrProcedimientos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.procedimientos.ctrProcedimientos ctrProcedimientos;
        
        /// <summary>
        /// CtrDxLista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.dx.CtrDxLista CtrDxLista;
        
        /// <summary>
        /// ctrHallazgos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.Hallazgos.ctrHallazgos ctrHallazgos;
        
        /// <summary>
        /// ctrNotas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.concurrencia.ctrNotas1 ctrNotas;
        
        /// <summary>
        /// ctrPtesConcur control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.concurrencia.CtrPtesConcur ctrPtesConcur;
        
        /// <summary>
        /// ctrFugas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.fugas.ctrFugas ctrFugas;
    }
}
