//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIISAConc.webControls.Hallazgos {
    
    
    public partial class ctrHallazgos {
        
        /// <summary>
        /// ddlTipoHallazgo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoHallazgo;
        
        /// <summary>
        /// ctrAreasAtencion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.areasAtencion.ctrAreasAtencion ctrAreasAtencion;
        
        /// <summary>
        /// ctrPertinencia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.pertinencia.ctrPertinencia ctrPertinencia;
        
        /// <summary>
        /// ctrInoportunidad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.inoportunidad.ctrInoportunidad ctrInoportunidad;
        
        /// <summary>
        /// ctrNoCalidad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.noCalidad.ctrNoCalidad ctrNoCalidad;
        
        /// <summary>
        /// ctrEventosAdversos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIISAConc.webControls.eventosAdversos.ctrEventosAdversos ctrEventosAdversos;
        
        /// <summary>
        /// txtHallazgo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtHallazgo;
        
        /// <summary>
        /// gvHallAtencion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvHallAtencion;
    }
}
